# GLOBAL-ANCHORS - DockerHub Authentication changes applied - PROD-1431 / PROD-1435
global_dockerhub_login: &global_dockerhub_login
  run:
    name: Authenticate with hub.docker.com - DockerHub
    command: docker login -u $GLOBAL_DOCKERHUB_USERNAME -p $GLOBAL_DOCKERHUB_PASSWORD
global_dockerhub_auth: &global_dockerhub_auth
  auth:
    username: $GLOBAL_DOCKERHUB_USERNAME
    password: $GLOBAL_DOCKERHUB_PASSWORD
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
        <<: *global_dockerhub_auth
    steps:
      - *global_dockerhub_login
      - checkout
      - run:
          name: Bundle Is Massive
          command: make install
      - run:
          name: Lint
          command: make lint
      - run:
          name: Test
          command: make test
